<!DOCTYPE html>
<html>
  <head>
    <title>Introduction to Java Programming, 10E, Y. Daniel Liang</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=5.0">
    <link rel="stylesheet" type="text/css" href="checkpoint.css" />
    <script type="text/javascript" src="jquery-latest.js"></script>

<script>var answer0 = 'The advantages of using exception handling: It enables a method to throw an exception to its caller. The caller can handle this exception. Without this capability, the called method itself must handle the exception or terminate the program. Often the called method does not know how to handle the exception. So it needs to pass the exception to its caller for handling.\
';function submit0() {if (document.getElementById('b0').innerHTML == 'Show Answer') {document.getElementById('a0').innerHTML = answer0;document.getElementById('b0').style.background = 'gray'; document.getElementById('b0').innerHTML = 'Hide Answer'; }else {document.getElementById('a0').innerHTML = '';
document.getElementById('b0').style.background = 'green'; document.getElementById('b0').innerHTML = 'Show Answer';} }</script>
<script>var answer1 = '\
<pre>\n\
System.out.println(1 / 0); // Throws an exception \n\
System.out.println(1.0 / 0); // Will not throw an exception\n\
</pre>\n\
';function submit1() {if (document.getElementById('b1').innerHTML == 'Show Answer') {document.getElementById('a1').innerHTML = answer1;document.getElementById('b1').style.background = 'gray'; document.getElementById('b1').innerHTML = 'Hide Answer'; }else {document.getElementById('a1').innerHTML = '';
document.getElementById('b1').style.background = 'green'; document.getElementById('b1').innerHTML = 'Show Answer';} }</script>
<script>var answer2 = 'Adding 1 to Long.MAX_VALUE exceeds the maximum value allowed by a long value. But the current versions of Java does not report this as an exception.\
';function submit2() {if (document.getElementById('b2').innerHTML == 'Show Answer') {document.getElementById('a2').innerHTML = answer2;document.getElementById('b2').style.background = 'gray'; document.getElementById('b2').innerHTML = 'Hide Answer'; }else {document.getElementById('a2').innerHTML = '';
document.getElementById('b2').style.background = 'green'; document.getElementById('b2').innerHTML = 'Show Answer';} }</script>
<script>var answer3 = '4.	When an excepion occurs, Java searches for a handler in the catch clause. So to catch an exception in your program, you need to write a try-catch statement like this:\
<pre>\n\
try {\n\
\n\
}\n\
catch (Exception ex) {\n\
  // Catch and process exception\n\
}\n\
</pre>\n\
';function submit3() {if (document.getElementById('b3').innerHTML == 'Show Answer') {document.getElementById('a3').innerHTML = answer3;document.getElementById('b3').style.background = 'gray'; document.getElementById('b3').innerHTML = 'Hide Answer'; }else {document.getElementById('a3').innerHTML = '';
document.getElementById('b3').style.background = 'green'; document.getElementById('b3').innerHTML = 'Show Answer';} }</script>
<script>var answer4 = 'output is \
            <pre>\n\
value is too small\n\
Continue after the catch block \n\
            </pre>\n\
 		The output would be if Line int value = 30; is changed to int value = 50;\
Continue after the catch block \
';function submit4() {if (document.getElementById('b4').innerHTML == 'Show Answer') {document.getElementById('a4').innerHTML = answer4;document.getElementById('b4').style.background = 'gray'; document.getElementById('b4').innerHTML = 'Hide Answer'; }else {document.getElementById('a4').innerHTML = '';
document.getElementById('b4').style.background = 'green'; document.getElementById('b4').innerHTML = 'Show Answer';} }</script>
<script>var answer5 = '\
<pre>\n\
a. 0 1\n\
b. 0\n\
</pre>\n\
';function submit5() {if (document.getElementById('b5').innerHTML == 'Show Answer') {document.getElementById('a5').innerHTML = answer5;document.getElementById('b5').style.background = 'gray'; document.getElementById('b5').innerHTML = 'Hide Answer'; }else {document.getElementById('a5').innerHTML = '';
document.getElementById('b5').style.background = 'green'; document.getElementById('b5').innerHTML = 'Show Answer';} }</script>
<script>var answer6 = 'See the section "Exceptions and Exception Types." The Throwable class is the root of Java exception classes. Error and Exception are subclasses of Throwable. Error describes fatal system errors, and Exception describes the errors that can be handled by Java programs. The subclasses of Error are LinkageError, VirtualMachineError, and AWTError. The subclasses of Exception include RuntimeException, IOException, AWTException, and InstantiationException.\
';function submit6() {if (document.getElementById('b6').innerHTML == 'Show Answer') {document.getElementById('a6').innerHTML = answer6;document.getElementById('b6').style.background = 'gray'; document.getElementById('b6').innerHTML = 'Hide Answer'; }else {document.getElementById('a6').innerHTML = '';
document.getElementById('b6').style.background = 'green'; document.getElementById('b6').innerHTML = 'Show Answer';} }</script>
<script>var answer7 = '\
a. ArithmeticException <br />\
b. ArrayIndexOutOfBoundsException <br />\
c. StringIndexOutOfBoundsException <br />\
d. ClassCastException <br />\
e. NullPointerException <br />\
f. No exception\
';function submit7() {if (document.getElementById('b7').innerHTML == 'Show Answer') {document.getElementById('a7').innerHTML = answer7;document.getElementById('b7').style.background = 'gray'; document.getElementById('b7').innerHTML = 'Hide Answer'; }else {document.getElementById('a7').innerHTML = '';
document.getElementById('b7').style.background = 'green'; document.getElementById('b7').innerHTML = 'Show Answer';} }</script>
<script>var answer8 = 'The purpose of declaring exceptions is to tell the Java runtime system what can go wrong. You declare an exception using the throws keyword in the method declaration. You can declare multiple exceptions, separated by commas.\
';function submit8() {if (document.getElementById('b8').innerHTML == 'Show Answer') {document.getElementById('a8').innerHTML = answer8;document.getElementById('b8').style.background = 'gray'; document.getElementById('b8').innerHTML = 'Hide Answer'; }else {document.getElementById('a8').innerHTML = '';
document.getElementById('b8').style.background = 'green'; document.getElementById('b8').innerHTML = 'Show Answer';} }</script>
<script>var answer9 = 'A checked exception must be explicitly declared in the method declaration, if a method throws it. A checked exception must be caught in a try-catch block. An unchecked exception does not need to be declared and does not need to be caught. In Java, the only unchecked exceptions are RuntimeException and Error and their subclasses.\
';function submit9() {if (document.getElementById('b9').innerHTML == 'Show Answer') {document.getElementById('a9').innerHTML = answer9;document.getElementById('b9').style.background = 'gray'; document.getElementById('b9').innerHTML = 'Hide Answer'; }else {document.getElementById('a9').innerHTML = '';
document.getElementById('b9').style.background = 'green'; document.getElementById('b9').innerHTML = 'Show Answer';} }</script>
<script>var answer10 = 'You use the throw statement in the method to throw an exception. You cannot throw multiple exceptions in a single throw statement.\
';function submit10() {if (document.getElementById('b10').innerHTML == 'Show Answer') {document.getElementById('a10').innerHTML = answer10;document.getElementById('b10').style.background = 'gray'; document.getElementById('b10').innerHTML = 'Hide Answer'; }else {document.getElementById('a10').innerHTML = '';
document.getElementById('b10').style.background = 'green'; document.getElementById('b10').innerHTML = 'Show Answer';} }</script>
<script>var answer11 = 'throw is for throwing exceptions and throws is for claiming exceptions.\
';function submit11() {if (document.getElementById('b11').innerHTML == 'Show Answer') {document.getElementById('a11').innerHTML = answer11;document.getElementById('b11').style.background = 'gray'; document.getElementById('b11').innerHTML = 'Hide Answer'; }else {document.getElementById('a11').innerHTML = '';
document.getElementById('b11').style.background = 'green'; document.getElementById('b11').innerHTML = 'Show Answer';} }</script>
<script>var answer12 = '1. No. <br />\
\
	2. No. <br />\
\
	3. Yes.\
';function submit12() {if (document.getElementById('b12').innerHTML == 'Show Answer') {document.getElementById('a12').innerHTML = answer12;document.getElementById('b12').style.background = 'gray'; document.getElementById('b12').innerHTML = 'Hide Answer'; }else {document.getElementById('a12').innerHTML = '';
document.getElementById('b12').style.background = 'green'; document.getElementById('b12').innerHTML = 'Show Answer';} }</script>
<script>var answer13 = '\
            <pre>\n\
            RuntimeException\n\
            </pre>\n\
	Reason: list[10] throws ArrayIndexOutOfBoundsException that is a subclass of RuntimeException.\
';function submit13() {if (document.getElementById('b13').innerHTML == 'Show Answer') {document.getElementById('a13').innerHTML = answer13;document.getElementById('b13').style.background = 'gray'; document.getElementById('b13').innerHTML = 'Hide Answer'; }else {document.getElementById('a13').innerHTML = '';
document.getElementById('b13').style.background = 'green'; document.getElementById('b13').innerHTML = 'Show Answer';} }</script>
<script>var answer14 = '\
            <pre>\n\
            ArithmeticException\n\
</pre>\n\
            Reason: method() throws ArithmeticException.\
';function submit14() {if (document.getElementById('b14').innerHTML == 'Show Answer') {document.getElementById('a14').innerHTML = answer14;document.getElementById('b14').style.background = 'gray'; document.getElementById('b14').innerHTML = 'Hide Answer'; }else {document.getElementById('a14').innerHTML = '';
document.getElementById('b14').style.background = 'green'; document.getElementById('b14').innerHTML = 'Show Answer';} }</script>
<script>var answer15 = '\
            <pre>\n\
            RuntimeException in method() After the method call  \n\
            </pre>\n\
            Reason: s.charAt(3) throws StringIndexOutOfBoundsException that is a subclass of RuntimeException. This exception is caught in method(). \
            The main method continues its normal execution flow.\
';function submit15() {if (document.getElementById('b15').innerHTML == 'Show Answer') {document.getElementById('a15').innerHTML = answer15;document.getElementById('b15').style.background = 'gray'; document.getElementById('b15').innerHTML = 'Hide Answer'; }else {document.getElementById('a15').innerHTML = '';
document.getElementById('b15').style.background = 'green'; document.getElementById('b15').innerHTML = 'Show Answer';} }</script>
<script>var answer16 = 'the getMessage() is defined in the \
            Throwable class to return a string that describes the exception. \
';function submit16() {if (document.getElementById('b16').innerHTML == 'Show Answer') {document.getElementById('a16').innerHTML = answer16;document.getElementById('b16').style.background = 'gray'; document.getElementById('b16').innerHTML = 'Hide Answer'; }else {document.getElementById('a16').innerHTML = '';
document.getElementById('b16').style.background = 'green'; document.getElementById('b16').innerHTML = 'Show Answer';} }</script>
<script>var answer17 = 'To display trace information to the console.\
';function submit17() {if (document.getElementById('b17').innerHTML == 'Show Answer') {document.getElementById('a17').innerHTML = answer17;document.getElementById('b17').style.background = 'gray'; document.getElementById('b17').innerHTML = 'Hide Answer'; }else {document.getElementById('a17').innerHTML = '';
document.getElementById('b17').style.background = 'green'; document.getElementById('b17').innerHTML = 'Show Answer';} }</script>
<script>var answer18 = 'No\
';function submit18() {if (document.getElementById('b18').innerHTML == 'Show Answer') {document.getElementById('a18').innerHTML = answer18;document.getElementById('b18').style.background = 'gray'; document.getElementById('b18').innerHTML = 'Hide Answer'; }else {document.getElementById('a18').innerHTML = '';
document.getElementById('b18').style.background = 'green'; document.getElementById('b18').innerHTML = 'Show Answer';} }</script>
<script>var answer19 = 'The method throws a checked exception. It must be caught or thrown. You may fix it as follows:\
<pre>\n\
public void m(int value) throws Exception {\n\
  if (value &lt; 40)\n\
    throw new Exception("value is too small");    \n\
}\n\
</pre>\n\
';function submit19() {if (document.getElementById('b19').innerHTML == 'Show Answer') {document.getElementById('a19').innerHTML = answer19;document.getElementById('b19').style.background = 'gray'; document.getElementById('b19').innerHTML = 'Hide Answer'; }else {document.getElementById('a19').innerHTML = '';
document.getElementById('b19').style.background = 'green'; document.getElementById('b19').innerHTML = 'Show Answer';} }</script>
<script>var answer20 = '1. Yes to both. <br />\
\
2. This exception is caught by the catch \
            (Exception1 e1) clause and statement4 will be executed and \
            statement5 will also be executed. <br />\
\
3. statement4 be executed, but statement5 will not be executed.\
';function submit20() {if (document.getElementById('b20').innerHTML == 'Show Answer') {document.getElementById('a20').innerHTML = answer20;document.getElementById('b20').style.background = 'gray'; document.getElementById('b20').innerHTML = 'Hide Answer'; }else {document.getElementById('a20').innerHTML = '';
document.getElementById('b20').style.background = 'green'; document.getElementById('b20').innerHTML = 'Show Answer';} }</script>
<script>var answer21 = 'Yes. It is correct. But a better way to write this method is using regular expression to test if the string is numeric.\
';function submit21() {if (document.getElementById('b21').innerHTML == 'Show Answer') {document.getElementById('a21').innerHTML = answer21;document.getElementById('b21').style.background = 'gray'; document.getElementById('b21').innerHTML = 'Hide Answer'; }else {document.getElementById('a21').innerHTML = '';
document.getElementById('b21').style.background = 'green'; document.getElementById('b21').innerHTML = 'Show Answer';} }</script>
<script>var answer22 = '1. Yes to both. <br />\
\
2. Yes to both. <br />\
\
3. This exception is caught by the catch (Exception2 e2) clause and statement4 \
            will be executed, but statement5 will not be executed because \
            it is rethrown to its caller. <br />\
\
4. This exception is not caught. statement4 will be executed, but statement5 will not be executed.\
';function submit22() {if (document.getElementById('b22').innerHTML == 'Show Answer') {document.getElementById('a22').innerHTML = answer22;document.getElementById('b22').style.background = 'gray'; document.getElementById('b22').innerHTML = 'Hide Answer'; }else {document.getElementById('a22').innerHTML = '';
document.getElementById('b22').style.background = 'green'; document.getElementById('b22').innerHTML = 'Show Answer';} }</script>
<script>var answer23 = 'The output will be\
            <pre>\n\
java.lang.Exception: New info from method1\n\
	at ChainedExceptionDemo.method1(ChainedExceptionDemo.java:16)\n\
	at ChainedExceptionDemo.main(ChainedExceptionDemo.java:4)\n\
            </pre>\n\
';function submit23() {if (document.getElementById('b23').innerHTML == 'Show Answer') {document.getElementById('a23').innerHTML = answer23;document.getElementById('b23').style.background = 'gray'; document.getElementById('b23').innerHTML = 'Hide Answer'; }else {document.getElementById('a23').innerHTML = '';
document.getElementById('b23').style.background = 'green'; document.getElementById('b23').innerHTML = 'Show Answer';} }</script>
<script>var answer24 = 'To define a custom class, extend Exception or a subclass of Exception.\
';function submit24() {if (document.getElementById('b24').innerHTML == 'Show Answer') {document.getElementById('a24').innerHTML = answer24;document.getElementById('b24').style.background = 'gray'; document.getElementById('b24').innerHTML = 'Hide Answer'; }else {document.getElementById('a24').innerHTML = '';
document.getElementById('b24').style.background = 'green'; document.getElementById('b24').innerHTML = 'Show Answer';} }</script>
<script>var answer25 = '\
<pre>\n\
Exception in method()\n\
Exception in main\n\
</pre>\n\
Reason: the setRadius method throws a RadiusException. RadiusException is a subclass of Exception. So it is caught in method()&#39;s handler. The handler rethrows it back to the main method. \
';function submit25() {if (document.getElementById('b25').innerHTML == 'Show Answer') {document.getElementById('a25').innerHTML = answer25;document.getElementById('b25').style.background = 'gray'; document.getElementById('b25').innerHTML = 'Hide Answer'; }else {document.getElementById('a25').innerHTML = '';
document.getElementById('b25').style.background = 'green'; document.getElementById('b25').innerHTML = 'Show Answer';} }</script>
<script>var answer26 = 'The \ is a special character. It should be written as \\ in Java using the Escape sequence.\
';function submit26() {if (document.getElementById('b26').innerHTML == 'Show Answer') {document.getElementById('a26').innerHTML = answer26;document.getElementById('b26').style.background = 'gray'; document.getElementById('b26').innerHTML = 'Hide Answer'; }else {document.getElementById('a26').innerHTML = '';
document.getElementById('b26').style.background = 'green'; document.getElementById('b26').innerHTML = 'Show Answer';} }</script>
<script>var answer27 = '28.	Use exists() in the File class to check whether a file exists. Use delete() in the File class to delete this file.  Use renameTo(File) to rename the name for this file. You cannot find the file size using the File class.\
';function submit27() {if (document.getElementById('b27').innerHTML == 'Show Answer') {document.getElementById('a27').innerHTML = answer27;document.getElementById('b27').style.background = 'gray'; document.getElementById('b27').innerHTML = 'Hide Answer'; }else {document.getElementById('a27').innerHTML = '';
document.getElementById('b27').style.background = 'green'; document.getElementById('b27').innerHTML = 'Show Answer';} }</script>
<script>var answer28 = 'No. The File class can be used to obtain file properties and manipulate files, but cannot perform I/O.\
';function submit28() {if (document.getElementById('b28').innerHTML == 'Show Answer') {document.getElementById('a28').innerHTML = answer28;document.getElementById('b28').style.background = 'gray'; document.getElementById('b28').innerHTML = 'Hide Answer'; }else {document.getElementById('a28').innerHTML = '';
document.getElementById('b28').style.background = 'green'; document.getElementById('b28').innerHTML = 'Show Answer';} }</script>
<script>var answer29 = 'To create a PrintWriter for a file, use new PrintWriter(filename). This statement may throw an exception. Java forces you to write the code to deal with exceptions. One way to deal with it is to declare throws Exception in the method declaration. \
            If the close() method is not invoked, the data may not be saved properly. \
';function submit29() {if (document.getElementById('b29').innerHTML == 'Show Answer') {document.getElementById('a29').innerHTML = answer29;document.getElementById('b29').style.background = 'gray'; document.getElementById('b29').innerHTML = 'Hide Answer'; }else {document.getElementById('a29').innerHTML = '';
document.getElementById('b29').style.background = 'green'; document.getElementById('b29').innerHTML = 'Show Answer';} }</script>
<script>var answer30 = '\
            The contents of the file temp.txt is:\
            <pre>\n\
amount is 32.320000 3.232000e+01\n\
amount is 32.3200 3.2320e+01\n\
 false\n\
  Java\n\
            </pre>\n\
';function submit30() {if (document.getElementById('b30').innerHTML == 'Show Answer') {document.getElementById('a30').innerHTML = answer30;document.getElementById('b30').style.background = 'gray'; document.getElementById('b30').innerHTML = 'Hide Answer'; }else {document.getElementById('a30').innerHTML = '';
document.getElementById('b30').style.background = 'green'; document.getElementById('b30').innerHTML = 'Show Answer';} }</script>
<script>var answer31 = '            <pre>\n\
public class Test {\n\
  public static void main(String[] args) throws Exception {\n\
    try (java.io.PrintWriter output = new \n\
      java.io.PrintWriter("temp.txt");) {\n\
      output.printf("amount is %f %e\r\n", 32.32, 32.32);\n\
      output.printf("amount is %5.4f %5.4e\r\n", 32.32, 32.32);\n\
      output.printf("%6b\r\n", (1 > 2));\n\
      output.printf("%6s\r\n", "Java");\n\
    }\n\
  }\n\
}\n\
</pre>\n\
';function submit31() {if (document.getElementById('b31').innerHTML == 'Show Answer') {document.getElementById('a31').innerHTML = answer31;document.getElementById('b31').style.background = 'gray'; document.getElementById('b31').innerHTML = 'Hide Answer'; }else {document.getElementById('a31').innerHTML = '';
document.getElementById('b31').style.background = 'green'; document.getElementById('b31').innerHTML = 'Show Answer';} }</script>
<script>var answer32 = 'To create a Scanner for a file, use new Scanner(new File(filename)). This statement may throw an exception. Java forces you to write the code to deal with exceptions. One way to deal with it is to declare throws Exception in the method declaration. If the close() method is not invoked, the problem will run fine. But it is a good practice to close the file to release the resource on the file.\
';function submit32() {if (document.getElementById('b32').innerHTML == 'Show Answer') {document.getElementById('a32').innerHTML = answer32;document.getElementById('b32').style.background = 'gray'; document.getElementById('b32').innerHTML = 'Hide Answer'; }else {document.getElementById('a32').innerHTML = '';
document.getElementById('b32').style.background = 'green'; document.getElementById('b32').innerHTML = 'Show Answer';} }</script>
<script>var answer33 = 'If you attempt to create a Scanner for a nonexistent file, \
            an exception will occur. If you attempt to create a Formatter \
            for an existing file, the contents of the existing file will be \
            gone.\
';function submit33() {if (document.getElementById('b33').innerHTML == 'Show Answer') {document.getElementById('a33').innerHTML = answer33;document.getElementById('b33').style.background = 'gray'; document.getElementById('b33').innerHTML = 'Hide Answer'; }else {document.getElementById('a33').innerHTML = '';
document.getElementById('b33').style.background = 'green'; document.getElementById('b33').innerHTML = 'Show Answer';} }</script>
<script>var answer34 = 'No. The line separator on Windows is \r\n.\
';function submit34() {if (document.getElementById('b34').innerHTML == 'Show Answer') {document.getElementById('a34').innerHTML = answer34;document.getElementById('b34').style.background = 'gray'; document.getElementById('b34').innerHTML = 'Hide Answer'; }else {document.getElementById('a34').innerHTML = '';
document.getElementById('b34').style.background = 'green'; document.getElementById('b34').innerHTML = 'Show Answer';} }</script>
<script>var answer35 = 'intValue contains 45. doubleValue contains 57.8, and line contains &#39;  &#39;, &#39;7 &#39;, &#39;8 &#39;, &#39;9&#39;.\
';function submit35() {if (document.getElementById('b35').innerHTML == 'Show Answer') {document.getElementById('a35').innerHTML = answer35;document.getElementById('b35').style.background = 'gray'; document.getElementById('b35').innerHTML = 'Hide Answer'; }else {document.getElementById('a35').innerHTML = '';
document.getElementById('b35').style.background = 'green'; document.getElementById('b35').innerHTML = 'Show Answer';} }</script>
<script>var answer36 = 'intValue contains 45. doubleValue contains 57.8, and line is empty.\
';function submit36() {if (document.getElementById('b36').innerHTML == 'Show Answer') {document.getElementById('a36').innerHTML = answer36;document.getElementById('b36').style.background = 'gray'; document.getElementById('b36').innerHTML = 'Hide Answer'; }else {document.getElementById('a36').innerHTML = '';
document.getElementById('b36').style.background = 'green'; document.getElementById('b36').innerHTML = 'Show Answer';} }</script>
<script>var answer37 = 'Create a URL object and use new Scanner(url.openStream()) to create a scanner object for reading data from the URL stream.\
';function submit37() {if (document.getElementById('b37').innerHTML == 'Show Answer') {document.getElementById('a37').innerHTML = answer37;document.getElementById('b37').style.background = 'gray'; document.getElementById('b37').innerHTML = 'Hide Answer'; }else {document.getElementById('a37').innerHTML = '';
document.getElementById('b37').style.background = 'green'; document.getElementById('b37').innerHTML = 'Show Answer';} }</script>
<script>var answer38 = 'Yes. Possible. Suppose link1 is not in listOfTraversedURLs, but it appears more than one time in a page. \
            Duplicate link1 will be added into listOfPendingURLs.\
';function submit38() {if (document.getElementById('b38').innerHTML == 'Show Answer') {document.getElementById('a38').innerHTML = answer38;document.getElementById('b38').style.background = 'gray'; document.getElementById('b38').innerHTML = 'Hide Answer'; }else {document.getElementById('a38').innerHTML = '';
document.getElementById('b38').style.background = 'green'; document.getElementById('b38').innerHTML = 'Show Answer';} }</script>
</head>
  <body>
     <div style = "text-align: center; color: navy; ">Please send suggestions and errata to Dr. Liang at <a href="mailto:y.daniel.liang@gmail.com" style="text-decoration: none; color: green">y.daniel.liang@gmail.com</a>. Indicate the book, edition, and question number in your email. Thanks!</div>    <div id="maincontentstyle">
      <center>
        <div id="boxstyle">
          <h3 id="h3style">Chapter 12 Check Point Questions</h3>
          
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.1</span>
What is the advantage of using exception handling?
                </div>
                <div id = "a0" class="answer"></div>
                <button id = "b0" type="button" class = "button" onclick="submit0()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.2</span>
Which of the following statements will throw an exception?
<pre>
    System.out.println(<span class = "constant">1</span> / <span class = "constant">0</span>);
    System.out.println(<span class = "constant">1</span><span class = "literal">.</span><span class = "constant">0</span> / <span class = "constant">0</span>);
</pre>
                </div>
                <div id = "a1" class="answer"></div>
                <button id = "b1" type="button" class = "button" onclick="submit1()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.3</span>
Point out the problem in the following code. Does the code throw any exceptions?
<pre>
    <span class = "keyword">long</span> value = Long.MAX_VALUE + <span class = "constant">1</span>;
    System.out.println(value);
</pre>
                </div>
                <div id = "a2" class="answer"></div>
                <button id = "b2" type="button" class = "button" onclick="submit2()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.4</span>
What does the JVM do when an exception occurs? How do you catch an exception?
                </div>
                <div id = "a3" class="answer"></div>
                <button id = "b3" type="button" class = "button" onclick="submit3()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.5</span>
What is the output of the following code?
<pre>
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        <span class = "keyword">try</span> {
          <span class = "keyword">int</span> value = <span class = "constant">30</span>;
          <span class = "keyword">if</span> (value &lt; <span class = "constant">40</span>)
            <span class = "keyword">throw</span> <span class = "keyword">new</span> Exception(<span class = "literal">"value is too small"</span>);
        }    
        <span class = "keyword">catch</span> (Exception ex) {
          System.out.println(ex.getMessage());
        }
        System.out.println(<span class = "literal">"Continue after the catch block"</span>);
      }
    }
</pre>
            What would be the output if the line
<pre>
    <span class = "keyword">int</span> value = <span class = "constant">30</span>;
    were changed to
    <span class = "keyword">int</span> value = <span class = "constant">50</span>;
</pre>
                </div>
                <div id = "a4" class="answer"></div>
                <button id = "b4" type="button" class = "button" onclick="submit4()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.6</span>

    Show the output of the following code.
<pre>
    (a)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        <span class = "keyword">for</span> (<span class = "keyword">int</span> i = <span class = "constant">0</span>; i &lt; <span class = "constant">2</span>; i++) {
          System.out.print(i + <span class = "literal">" "</span>);
          <span class = "keyword">try</span> {
            System.out.println(<span class = "constant">1</span> / <span class = "constant">0</span>);
          }
          <span class = "keyword">catch</span> (Exception ex) {
          }
        }
      }
    }

    (b)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        <span class = "keyword">try</span> {
          <span class = "keyword">for</span> (<span class = "keyword">int</span> i = <span class = "constant">0</span>; i &lt; <span class = "constant">2</span>; i++) {
            System.out.print(i + <span class = "literal">" "</span>);
            System.out.println(<span class = "constant">1</span> / <span class = "constant">0</span>);
              }
        }
        <span class = "keyword">catch</span> (Exception ex) {
        }
      }
    }
</pre>
                </div>
                <div id = "a5" class="answer"></div>
                <button id = "b5" type="button" class = "button" onclick="submit5()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.7</span>
Describe the Java Throwable class, its subclasses, and the types of exceptions.
                </div>
                <div id = "a6" class="answer"></div>
                <button id = "b6" type="button" class = "button" onclick="submit6()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.8</span>
What RuntimeException will the following programs throw, if any?
<pre>
    (a)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        System.out.println(<span class = "constant">1</span> / <span class = "constant">0</span>);
      }
    }

    (b)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        <span class = "keyword">int</span>[] list = <span class = "keyword">new</span> <span class = "keyword">int</span>[<span class = "constant">5</span>];
        System.out.println(list[<span class = "constant">5</span>]);
      }
    }

    (c) 
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        String s = <span class = "literal">"abc"</span>;
        System.out.println(s.charAt(<span class = "constant">3</span>));
      }
    }

    (d)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        Object o = <span class = "keyword">new</span> Object();
        String d = (String)o;
      }
    }

    (e)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        Object o = <span class = "keyword">null</span>;
        System.out.println(o.toString());
      }
    }

    (f)
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        System.out.println(<span class = "constant">1</span><span class = "literal">.</span><span class = "constant">0</span> / <span class = "constant">0</span>);
      }
    }
</pre>
                </div>
                <div id = "a7" class="answer"></div>
                <button id = "b7" type="button" class = "button" onclick="submit7()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.9</span>
What is the purpose of declaring exceptions? How do you declare an exception, and where? Can you declare multiple exceptions in a method header?
                </div>
                <div id = "a8" class="answer"></div>
                <button id = "b8" type="button" class = "button" onclick="submit8()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.10</span>
What is a checked exception, and what is an unchecked exception?
                </div>
                <div id = "a9" class="answer"></div>
                <button id = "b9" type="button" class = "button" onclick="submit9()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.11</span>
 How do you throw an exception? Can you throw multiple exceptions in one throw statement?
                </div>
                <div id = "a10" class="answer"></div>
                <button id = "b10" type="button" class = "button" onclick="submit10()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.12</span>
What is the keyword throw used for? What is the keyword throws used for?
                </div>
                <div id = "a11" class="answer"></div>
                <button id = "b11" type="button" class = "button" onclick="submit11()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.13</span>
Suppose that statement2 causes an exception in the following try-catch block:
<pre>
    <span class = "keyword">try</span> {
      statement1;
      statement2;
      statement3;
    }
    <span class = "keyword">catch</span> (Exception1 ex1) {
    }
    <span class = "keyword">catch</span> (Exception2 ex2) {
    }

    statement4;
</pre>
	Answer the following questions: <br />
	1. Will statement3 be executed? <br />
	2. If the exception is not caught, will statement4 be executed? <br />
	3. If the exception is caught in the catch block, will statement4 be executed?
                </div>
                <div id = "a12" class="answer"></div>
                <button id = "b12" type="button" class = "button" onclick="submit12()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.14</span>
What is displayed when the following program is run?
<pre>
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        <span class = "keyword">try</span> {
          <span class = "keyword">int</span>[] list = <span class = "keyword">new</span> <span class = "keyword">int</span>[<span class = "constant">10</span>];
          System.out.println(<span class = "literal">"list[<span class = "constant">10</span>] is "</span> + list[<span class = "constant">10</span>]);      
        }   
        <span class = "keyword">catch</span> (ArithmeticException ex) {
          System.out.println(<span class = "literal">"ArithmeticException"</span>);   
        }   
        <span class = "keyword">catch</span> (RuntimeException ex) {
          System.out.println(<span class = "literal">"RuntimeException"</span>);   
        }   
        <span class = "keyword">catch</span> (Exception ex) {   
          System.out.println(<span class = "literal">"Exception"</span>);   
        }   
      }
    }
</pre>
                </div>
                <div id = "a13" class="answer"></div>
                <button id = "b13" type="button" class = "button" onclick="submit13()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.15</span>
What is displayed when the following program is run?
<pre>
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {  
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) { 
        <span class = "keyword">try</span> {
          method();
          System.out.println(<span class = "literal">"After the method call"</span>);   
        }   
        <span class = "keyword">catch</span> (ArithmeticException ex) { 
          System.out.println(<span class = "literal">"ArithmeticException"</span>);   
        }   
        <span class = "keyword">catch</span> (RuntimeException ex) { 
          System.out.println(<span class = "literal">"RuntimeException"</span>);   
        }   
        <span class = "keyword">catch</span> (Exception e) {
          System.out.println(<span class = "literal">"Exception"</span>);  
        }   
      }

      <span class = "keyword">static</span> <span class = "keyword">void</span> method() <span class = "keyword">throws</span> Exception {
        System.out.println(<span class = "constant">1</span> / <span class = "constant">0</span>);
      }
    }
</pre>
                </div>
                <div id = "a14" class="answer"></div>
                <button id = "b14" type="button" class = "button" onclick="submit14()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.16</span>
What is displayed when the following program is run?
<pre>
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test { 
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) {
        <span class = "keyword">try</span> {
          method();
          System.out.println(<span class = "literal">"After the method call"</span>);   
        }   
        <span class = "keyword">catch</span> (RuntimeException ex) {
          System.out.println(<span class = "literal">"RuntimeException in main"</span>);   
        }   
        <span class = "keyword">catch</span> (Exception ex) {
          System.out.println(<span class = "literal">"Exception in main"</span>);   
        }   
      }

      <span class = "keyword">static</span> <span class = "keyword">void</span> method() <span class = "keyword">throws</span> Exception {
        <span class = "keyword">try</span> {
          String s ="abc"</span>;
          System.out.println(s.charAt(<span class = "constant">3</span>));
        }
        <span class = "keyword">catch</span> (RuntimeException ex) {
          System.out.println(<span class = "literal">"RuntimeException in method()"</span>);   
        }   
        <span class = "keyword">catch</span> (Exception ex) {
          System.out.println(<span class = "literal">"Exception in method()"</span>);   
        }
      }
    }
</pre>
                </div>
                <div id = "a15" class="answer"></div>
                <button id = "b15" type="button" class = "button" onclick="submit15()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.17</span>
What does the method getMessage() do?
                </div>
                <div id = "a16" class="answer"></div>
                <button id = "b16" type="button" class = "button" onclick="submit16()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.18</span>
What does the method printStackTrace() do?
                </div>
                <div id = "a17" class="answer"></div>
                <button id = "b17" type="button" class = "button" onclick="submit17()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.19</span>
Does the presence of a try-catch block impose 
            overhead when no exception occurs?
                </div>
                <div id = "a18" class="answer"></div>
                <button id = "b18" type="button" class = "button" onclick="submit18()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.20</span>
Correct a compile error in the following code:
<pre>
    <span class = "keyword">public</span> <span class = "keyword">void</span> m(<span class = "keyword">int</span> value) {
      <span class = "keyword">if</span> (value &lt; <span class = "constant">40</span>)
        <span class = "keyword">throw</span> <span class = "keyword">new</span> Exception(<span class = "literal">"value is too small"</span>);    
    }
</pre>
                </div>
                <div id = "a19" class="answer"></div>
                <button id = "b19" type="button" class = "button" onclick="submit19()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.21</span>
Suppose that statement2 causes an exception in the following statement:
<pre>
    <span class = "keyword">try</span> {
      statement1;
      statement2;
      statement3;
    }
    <span class = "keyword">catch</span> (Exception1 ex1) {
    }
    <span class = "keyword">finally</span> {
      statement4;
    }
    statement5;
</pre>
            Answer the following questions: <br />
1. If no exception occurs, will statement4 be executed, and will statement5 be executed? <br />
2. If the exception is of type Exception1, will statement4 be executed, and will statement5 be executed? <br />
3. If the exception is not of type Exception1, will statement4 be executed, and will statement5 be executed?
                </div>
                <div id = "a20" class="answer"></div>
                <button id = "b20" type="button" class = "button" onclick="submit20()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.22</span>
The following method tests whether a string is a numeric string:
<pre>
    <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">boolean</span> isNumeric(String token) {
      <span class = "keyword">try</span> {
        Double.parseDouble(token);
        <span class = "keyword">return</span> <span class = "keyword">true</span>;
      }
      <span class = "keyword">catch</span> (java.lang.NumberFormatException ex) {
        <span class = "keyword">return</span> <span class = "keyword">false</span>;
      }
    }
</pre>
            Is it correct? Rewrite it without using exceptions.
                </div>
                <div id = "a21" class="answer"></div>
                <button id = "b21" type="button" class = "button" onclick="submit21()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.23</span>
Suppose that statement2 causes an exception in the following statement:
<pre>
    <span class = "keyword">try</span> {
      statement1;
      statement2;
      statement3;
    }
    <span class = "keyword">catch</span> (Exception1 ex1) {
    }
    <span class = "keyword">catch</span> (Exception2 ex2) {
      <span class = "keyword">throw</span> ex2;
    }
    <span class = "keyword">finally</span> {
      statement4;
    }
    statement5;
</pre>
	Answer the following questions: <br />
1. If no exception occurs, will statement4 be executed, and will statement5 be executed? <br />
2. If the exception is of type Exception1, will statement4 be executed, and will statement5 be executed? <br />
3. If the exception is of type Exception2, will statement4 be executed, and will statement5 be executed? <br />
4. If the exception is not Exception1 nor Exception2, will statement4 be executed, and will statement5 be executed?
                </div>
                <div id = "a22" class="answer"></div>
                <button id = "b22" type="button" class = "button" onclick="submit22()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.24</span>
What would be the output if line 16 is replaced by the following line?
<pre>
     <span class = "keyword">throw</span> <span class = "keyword">new</span> Exception(<span class = "literal">"New info from method1"</span>);
</pre>
                </div>
                <div id = "a23" class="answer"></div>
                <button id = "b23" type="button" class = "button" onclick="submit23()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.25</span>
How do you define a custom exception class?
                </div>
                <div id = "a24" class="answer"></div>
                <button id = "b24" type="button" class = "button" onclick="submit24()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.26</span>
Suppose the setRadius method throws the InValidRadiusException defined in 
                </div>
                <div id = "a25" class="answer"></div>
                <button id = "b25" type="button" class = "button" onclick="submit25()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.27</span>
What is wrong about creating a File object using the following statement?
<pre>
    <span class = "keyword">new</span> File(<span class = "literal">"c:\book\test.dat"</span>);
</pre>
                </div>
                <div id = "a26" class="answer"></div>
                <button id = "b26" type="button" class = "button" onclick="submit26()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.28</span>
 How do you check whether a file already exists? How do you delete a file? How do you rename a file? Can you find the file size (the number of bytes) using the File class? How do you create a directory?
                </div>
                <div id = "a27" class="answer"></div>
                <button id = "b27" type="button" class = "button" onclick="submit27()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.29</span>
Can you use the File class for I/O? Does creating a File object create a file on the disk?
                </div>
                <div id = "a28" class="answer"></div>
                <button id = "b28" type="button" class = "button" onclick="submit28()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.30</span>
How do you create a PrintWriter to write data to a file? What is the reason to declare throws Exception in the 
            main method in Listing 12.13, WriteData.java? What would happen if the close() method were not invoked in 
                </div>
                <div id = "a29" class="answer"></div>
                <button id = "b29" type="button" class = "button" onclick="submit29()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.31</span>
Show the contents of the file temp.txt after the following program is executed.
<pre>
    <span class = "keyword">public</span> <span class = "keyword">class</span> Test {
      <span class = "keyword">public</span> <span class = "keyword">static</span> <span class = "keyword">void</span> main(String[] args) <span class = "keyword">throws</span> Exception {
        java.io.PrintWriter output = <span class = "keyword">new</span> 
          java.io.PrintWriter(<span class = "literal">"temp.txt"</span>);
        output.printf(<span class = "literal">"amount is %f %e\r\n"</span>, <span class = "constant">32</span><span class = "literal">.</span><span class = "constant">32</span>, <span class = "constant">32</span><span class = "literal">.</span><span class = "constant">32</span>);
        output.printf(<span class = "literal">"amount is %<span class = "constant">5</span><span class = "literal">.</span><span class = "constant">4f</span> %<span class = "constant">5</span><span class = "literal">.</span>4e\r\n"</span>, <span class = "constant">32</span><span class = "literal">.</span><span class = "constant">32</span>, <span class = "constant">32</span><span class = "literal">.</span><span class = "constant">32</span>);
        output.printf(<span class = "literal">"%6b\r\n"</span>, (<span class = "constant">1</span> > <span class = "constant">2</span>));
        output.printf(<span class = "literal">"%6s\r\n"</span>, <span class = "literal">"Java"</span>);
        output.close();
      }
    }
</pre>
                </div>
                <div id = "a30" class="answer"></div>
                <button id = "b30" type="button" class = "button" onclick="submit30()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.32</span>
Rewrite the code in the preceding question using a try-with-resources syntax.  
                </div>
                <div id = "a31" class="answer"></div>
                <button id = "b31" type="button" class = "button" onclick="submit31()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.33</span>
How do you create a Scanner to read data from a file? What is the reason to define throws Exception in the main method in 
                </div>
                <div id = "a32" class="answer"></div>
                <button id = "b32" type="button" class = "button" onclick="submit32()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.34</span>
What will happen if you attempt to create a Scanner for a nonexistent file? What will happen if you attempt to create a PrintWriter for an existing file?
                </div>
                <div id = "a33" class="answer"></div>
                <button id = "b33" type="button" class = "button" onclick="submit33()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.35</span>
 Is the line separator the same on all platforms? What is the line separator on Windows?
                </div>
                <div id = "a34" class="answer"></div>
                <button id = "b34" type="button" class = "button" onclick="submit34()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.36</span>
Suppose you enter 45 57.8 789, then press the Enter key. Show the contents of the variables after the following code is executed.
<pre>
    Scanner input = <span class = "keyword">new</span> Scanner(System.in);
    <span class = "keyword">int</span> intValue = input.nextInt();
    <span class = "keyword">double</span> doubleValue = input.nextDouble();
    String line = input.nextLine();
</pre>
                </div>
                <div id = "a35" class="answer"></div>
                <button id = "b35" type="button" class = "button" onclick="submit35()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.37</span>
Suppose you enter 45, press the Enter key, 57.8, press the Enter key, 789, and press the Enter key. Show the contents of the variables after the following code is executed.
<pre>
    Scanner input = <span class = "keyword">new</span> Scanner(System.in);
    <span class = "keyword">int</span> intValue = input.nextInt();
    <span class = "keyword">double</span> doubleValue = input.nextDouble();
    String line = input.nextLine();
</pre>
                </div>
                <div id = "a36" class="answer"></div>
                <button id = "b36" type="button" class = "button" onclick="submit36()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.38</span>
How do you create a Scanner object for reading text from a URL?
                </div>
                <div id = "a37" class="answer"></div>
                <button id = "b37" type="button" class = "button" onclick="submit37()">Show Answer</button>
            </div>
<div id="question"><div id="questionstatement">
              <span id="questionnumber">12.39</span>
Before a URL is added to listOfPendingURLs, line 25 tests whether it has been traversed. Is it possible that listOfPendingURLs contains duplicate URLs? If so, give an example.
                </div>
                <div id = "a38" class="answer"></div>
                <button id = "b38" type="button" class = "button" onclick="submit38()">Show Answer</button>
            </div>
        </div>
      </div>
      </div>
    </div>
  </body>
</html>
